# Generated by Django 3.2.7 on 2021-10-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20211021_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tipo',
        ),
    ]
